Fix incorrect terminate binding contract logic
evolutionary-architecture/evolutionary-architecture-by-example pull request #126
Opened 2024-05-02 06:00 UTC by meaboutsoftware

This PR includes changes related to:

- searching for binding contract using its id instead of contract id
- fix of the API path for binding contracts
- returning binding contract id while signing the contract
- adjusting access modifiers to internal
- renaming

2024-05-02 15:33 UTC, kamilbaczek requested changes

2024-05-02 15:33 UTC, kamilbaczek commented on Chapter-4-applying-tactical-domain-driven-design/Fitnet.Contracts/Src/Fitnet.Contracts.Api/ContractsApiPaths.cs
> +    private const string BindingContractsApi = $"{ApiPaths.Root}/bindingContracts";
```csharp
private const string BindingContractsApi = $"{ApiPaths.Root}/binding-contracts";
```  

What you think?

2024-05-02 15:33 UTC, kamilbaczek commented on Chapter-4-applying-tactical-domain-driven-design/Fitnet.Contracts/Src/Fitnet.Contracts.Api/SignContract/SignContractEndpoint.cs
> +            return Results.Ok(bindingContractId);
```csharp
return Results.Created($"/{ContractsApiPaths.BindingContracts}/{bindingContractId}", bindingContractId);
```

2024-05-02 15:33 UTC, kamilbaczek commented on Chapter-4-applying-tactical-domain-driven-design/Fitnet.Contracts/Src/Fitnet.Contracts.Api/SignContract/SignContractEndpoint.cs
> +        .Produces(StatusCodes.Status200OK)
```csharp
StatusCodes.201CREATED
```

2024-05-02 15:34 UTC, kamilbaczek commented
Please update .http documentation as well according to changing API

2024-05-03 06:00 UTC, meaboutsoftware commented on Chapter-4-applying-tactical-domain-driven-design/Fitnet.Contracts/Src/Fitnet.Contracts.Api/ContractsApiPaths.cs
> +    private const string BindingContractsApi = $"{ApiPaths.Root}/bindingContracts";
Done

2024-05-03 06:05 UTC, meaboutsoftware commented on Chapter-4-applying-tactical-domain-driven-design/Fitnet.Contracts/Src/Fitnet.Contracts.Api/SignContract/SignContractEndpoint.cs
> +        .Produces(StatusCodes.Status200OK)
Done

2024-05-03 06:05 UTC, meaboutsoftware commented on Chapter-4-applying-tactical-domain-driven-design/Fitnet.Contracts/Src/Fitnet.Contracts.Api/SignContract/SignContractEndpoint.cs
> +            return Results.Ok(bindingContractId);
Done

2024-05-03 14:29 UTC, kamilbaczek approved these changes
Great! Thanks 👍🏻

2024-05-03 14:52 UTC, merged