Feature/add api logic for attach annex
evolutionary-architecture/evolutionary-architecture-by-example pull request #128
Opened 2024-05-07 07:47 UTC by meaboutsoftware

This PR includes changes related to:

- return id of the annex when attached to binding contract
- add command and handler for attachment of annex
- add endpoint for attachment of annex
- cleanup of existing contracts tests to stick to convention (do not include status_code in method descriptions)

2024-05-07 16:21 UTC, kamilbaczek approved these changes
I suggested some small improvemnts. Overall looks very good!

2024-05-07 16:21 UTC, kamilbaczek commented on Chapter-4-applying-tactical-domain-driven-design/Fitnet.Contracts/Src/Fitnet.Contracts.Api/AttachAnnexToBindingContract/AttachAnnexToBindingContractEndpoint.cs
> +                Guid id,
Could we change to Guid bindingContractId?

2024-05-07 16:21 UTC, kamilbaczek requested changes
please check comments

2024-05-08 06:07 UTC, meaboutsoftware commented on Chapter-4-applying-tactical-domain-driven-design/Fitnet.Contracts/Src/Fitnet.Contracts.Core/BindingContract.cs
> +        return annex.Id;
It is already raised in Annex :)

2024-05-08 10:19 UTC, kamilbaczek approved these changes

2024-05-08 10:44 UTC, merged