Feature/chapter 3 fluent validations
evolutionary-architecture/evolutionary-architecture-by-example pull request #18
Opened 2023-09-10 13:53 UTC by kamilbaczek

2023-09-10 19:22 UTC, kamilbaczek commented on Chapter-3-microservice-extraction/Fitnet.Contracts/Src/Fitnet.Contracts.Api.UnitTests/Prepare/RequestValidator/PrepareContractRequestParameters.cs
> +internal sealed record PrepareContractRequestParameters(int MinAge, int MaxAge, int MinHeight, int MaxHeight)
I next PR this class should be reused move to some common testing fakers.

2023-09-11 06:03 UTC, meaboutsoftware requested changes

2023-09-11 06:03 UTC, meaboutsoftware commented on Chapter-3-microservice-extraction/Contracts/Src/Fitnet.Contracts.Api.UnitTests/Fitnet.Contracts.Api.UnitTests.csproj
> +<Project Sdk="Microsoft.NET.Sdk">
Have you rebased your version based on current one? Then Please do not forget to remove Contracts folder from Root and ModularMonolith (as they do not exist anymore - were both renamed)

2023-09-11 18:02 UTC, meaboutsoftware approved these changes

2023-09-11 18:08 UTC, merged